import type {Metadata} from "next";
import {DM_Sans, Geist, Geist_Mono} from "next/font/google";
import {ThemeProvider} from "@/components/theme-provider"; // Asegúrate de importar correctamente
import "./globals.css";

// Carga la fuente, opcionalmente indicando subsets, weights, styles
const dmSans = DM_Sans({
    subsets: ['latin'],   // o ['latin', 'latin-ext'] etc.
    weight: ['400', '500', '700'], // pesos que uses
    variable: '--font-dm-sans',  // para usarla como variable CSS
    display: 'swap',      // recomendación de Google
});

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="en" suppressHydrationWarning>
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
        {/* Theme provider wraps the entire app */}
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
        >
            {children}
        </ThemeProvider>
        </body>
        </html>
    );
}
